### PR TITLE
GeoWebCache update for JAI to ImageN rename of classes and constants

### PR DESCRIPTION
**Pull request by jodygarnett**
No direct API usage, apparnelty everythign is done via ImageWorker.

Concurrent merge of jai-rename branches:

* https://github.com/eclipse-imagen/imagen/pull/115
* https://github.com/geosolutions-it/imageio-ext/pull/334
* https://github.com/geotools/geotools/pull/5364
* https://github.com/mapfish/mapfish-print-v2/pull/39
* https://github.com/GeoWebCache/geowebcache/pull/1434
* https://github.com/geoserver/geoserver/pull/8821

Reviewers: This change requires these branches to be merged at the same time, see upstream [pull request](https://github.com/eclipse-imagen/imagen/pull/115) for a complete integration test of the jai-rename branches.

### CODE REVIEW

**Comment by aaime** [comment]
I cannot build the branch as-is (using renamed ImageN):

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.14.0:compile (default-compile) on project gwc-core: Compilation failure: Compilation failure: 
[ERROR] /home/aaime/devel/git-gwc/geowebcache/core/src/main/java/org/geowebcache/layer/MetaTile.java:[36,26] cannot find symbol
[ERROR]   symbol:   class JAI
[ERROR]   location: package org.eclipse.imagen
[ERROR] /home/aaime/devel/git-gwc/geowebcache/core/src/main/java/org/geowebcache/mime/ImageMime.java:[29,26] cannot find symbol
[ERROR]   symbol:   class JAI
[ERROR]   location: package org.eclipse.imagen
[ERROR] -> [Help 1]
[ERROR] 
```

I've made the necessary fixes and pushed a commit to this branch.

**Comment by jodygarnett** [comment]
Huh, it seems I failed to run the script before making the PR, let me try again and see if it catches this change.
